#!/bin/sh

case "$1" in
        start)
                if [ -e /dev/vehicle ] ; then
                        echo 88 > /dev/vehicle
                        [ $? = 0 ] && echo "OK" || echo "FAIL"
                else
                        echo "/dev/vehicle do not exist"
                fi
                ;;
        *)
                echo "Usage: $0 {start}"
                exit 1
esac

exit 0
