#!/bin/sh
#
# Start px3-se linux service/window....
#

case "$1" in
  start)
	printf "start rkwifi module"
	echo 1 >/sys/class/rkwifi/driver
	rkrtkbt  ttyS0 &
	printf "mount userdatafs:"
	mount -t jffs2 /dev/mtdblock4 /data
	;;
  stop)
	printf "stop rkwifi module"
	echo 0 >/sys/class/rkwifi/driver
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
