#!/bin/sh

/bin/busybox --install

[ -d /proc ] || mkdir /proc
mount -t proc proc /proc

[ -d /sys ] || mkdir /sys
mount -t sysfs sys /sys

[ -d /dev ] || mkdir /dev
mount -t devtmpfs dev /dev

[ -d /tmp ] || mkdir /tmp
mount -t tmpfs tmp /tmp

cd /dev
ln -s null tty2
ln -s null tty3
ln -s null tty4
cd /
